[tox]
envlist = py38, py39, py310, py311, flake8, mypy
isolated_build = true

[testenv]
deps =
    pytest
    pytest-cov
commands =
    pytest {posargs}

[testenv:flake8]
deps = flake8
commands = flake8 src tests

[testenv:mypy]
deps =
    mypy
    types-requests
commands = mypy src

[flake8]
max-line-length = 100
exclude =
    .git,
    __pycache__,
    build,
    dist,
    .tox,
    .venv
